services:
  app:
    build: .
    container_name: campusflow_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      SESSION_SECRET: clave_docker_campusflow
      NODE_ENV: production
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: campusflow_postgres
    restart: always
    environment:
      POSTGRES_DB: campusflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - campusflow_data:/var/lib/postgresql/data

volumes:
  campusflow_data: